version: '3.8'

services:

  app:

    build: .
    image: seu-usuario-docker/smartcollect-esg:latest
    container_name: smartcollect-app

    ports:
      - "${APP_PORT}:8080"

    environment:

      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      SPRING_DATASOURCE_USERNAME: SYSTEM
      SPRING_DATASOURCE_PASSWORD: ${ORACLE_PASSWORD}


      JAVA_OPTS: "-XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=75.0"

    depends_on:
       oracle-db:
          condition: service_healthy

    networks:
      - smartcollect-network

  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: smartcollect-oracle-db

    ports:
      - "1521:1521"

    environment:
      ORACLE_PWD: ${ORACLE_PASSWORD}

    volumes:
      - oracle-data:/opt/oracle/oradata

    restart: unless-stopped
    networks:
      - smartcollect-network

    healthcheck:
      test: [ "CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s SYSTEM/${ORACLE_PWD}@localhost:1521/FREEPDB1" ]
      interval: 20s
      timeout: 10s
      retries: 10

networks:
  smartcollect-network:
    driver: bridge

volumes:
  oracle-data: