-- SQL PARA CRIAÇÃO DAS TABELAS --
CREATE TABLE T_Ponto_Coleta (
                                id_ponto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                nome VARCHAR2(100) NOT NULL,
                                endereco VARCHAR2(200) NOT NULL,
                                capacidade_total NUMBER NOT NULL
);

CREATE TABLE T_Residuo (
                           id_residuo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           tipo VARCHAR2(50) NOT NULL,
                           descricao VARCHAR2(100) NOT NULL
);

CREATE TABLE T_Descarte (
                            id_descarte NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            T_Ponto_Coleta_id_ponto NUMBER NOT NULL,
                            T_Residuo_id_residuo NUMBER NOT NULL,
                            quantidade_kg NUMBER NOT NULL,
                            data_descarte DATE NOT NULL,
                            FOREIGN KEY (T_Ponto_Coleta_id_ponto) REFERENCES T_Ponto_Coleta(id_ponto),
                            FOREIGN KEY (T_Residuo_id_residuo) REFERENCES T_Residuo(id_residuo)
);

CREATE TABLE T_Coleta (
                          id_coleta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          T_Ponto_Coleta_id_ponto NUMBER NOT NULL,
                          data_coleta DATE,
                          quantidade_kg NUMBER,
                          FOREIGN KEY (T_Ponto_Coleta_id_ponto) REFERENCES T_Ponto_Coleta(id_ponto)
);

CREATE TABLE T_Alertas (
                           id_alerta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           T_Ponto_Coleta_id_ponto NUMBER NOT NULL,
                           data_alerta DATE,
                           mensagem VARCHAR2(200) NOT NULL,
                           resolvido CHAR(1),
                           FOREIGN KEY (T_Ponto_Coleta_id_ponto) REFERENCES T_Ponto_Coleta(id_ponto)
);