# =========================================================================
# ARQUIVO: .github/workflows/main.yml
# =========================================================================

name: CI/CD do Projeto SmartCollect

# O pipeline é disparado sempre que houver um push na branch 'main'
on:
  push:
    branches:
      - main

env:
  # Nome da Imagem no Docker Hub - SUBSTITUA PELO SEU USUÁRIO
  DOCKER_IMAGE_NAME: geovani237/smartcollect-esg
  DOCKER_REGISTRY: docker.io
  TAG: ${{ github.sha }}

jobs:
  # 1. BUILD E TESTES AUTOMATIZADOS (CI)
  build_and_test:
    name: Build e Testes com Maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Setup JDK 21 e Cache Maven
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Executar Build e Testes (Excluindo Banco de Dados)
          # Usa um argumento Maven para desabilitar a conexão com o banco
        run: mvn clean install -Dspring.profiles.active=test
      - name: Upload JAR como Artefato
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/smartcollect-0.0.1-SNAPSHOT.jar

  # 2. BUILD E PUSH DA IMAGEM DOCKER
  build_push_docker:
    name: Build e Push da Imagem
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: application-jar
          path: target/
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build e Push da Imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest

  # =========================================================================
  # 3. SIMULAÇÃO DE DEPLOY EM STAGING
  # =========================================================================
  deploy_staging:
    name: Simulação de Deploy em Staging
    needs: build_push_docker
    runs-on: ubuntu-latest
    environment: staging # Mantém o uso do ambiente

    steps:
      - name: Acessar Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Simulação de Deploy
        run: |
          echo "Simulando a conexão ao servidor de STAGING..."
          echo "1. Pull da imagem mais recente: ${{ env.DOCKER_IMAGE_NAME }}:latest"
          # Comando para "baixar" a imagem no ambiente de simulação
          docker pull ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          
          echo "2. Criação do arquivo .env com a senha segura (ORACLE_STAGING_PWD)."
          echo "3. Executando 'docker compose up' no STAGING..."
          echo "Deploy do ambiente STAGING concluído com sucesso."
          echo "A aplicação SmartCollect está rodando em http://staging.simulacao.com:8081" # Exibir URL/mensagem

  # =========================================================================
  # 4. SIMULAÇÃO DE DEPLOY EM PRODUÇÃO (Com Aprovação Manual)
  # =========================================================================
  deploy_production:
    name: Simulação de Deploy em Produção
    needs: deploy_staging
    runs-on: ubuntu-latest
    # Configura o ambiente de produção com REVISOR OBRIGATÓRIO (mantém o fluxo de CD)
    environment:
      name: production
      url: https://smartcollect.simulacao.com # URL para evidência

    steps:
      - name: Acessar Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Simulação de Deploy
        run: |
          echo "SIMULANDO APROVAÇÃO MANUAL PARA PRODUÇÃO..."
          echo "1. Pull da imagem mais recente: ${{ env.DOCKER_IMAGE_NAME }}:latest"
          docker pull ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest

          echo "2. Criação do arquivo .env com a senha ultra-segura (ORACLE_PROD_PWD)."
          echo "3. Executando 'docker compose up' no PRODUÇÃO..."
          echo "DEPLOY FINALIZADO! A aplicação SmartCollect está rodando em produção."
          echo "Verifique o funcionamento em https://smartcollect.simulacao.com" # Mensagem final para evidência