name: CI/CD

on:
  push:
    branches:
      - main
      - staging

jobs:
  build_and_test:
    name: Build e Testes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build e Testes
        run: mvn clean install

  docker_build_and_push:
    name: Build e Push Docker
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build da Imagem Docker
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/smartcollect:${{ github.sha }} .
      - name: Push da Imagem Docker
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/smartcollect:${{ github.sha }}

  deploy_cloud:
    name: Deploy em Cloud
    needs: docker_build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy para Plataforma Cloud
        run: echo "Adapte este passo para sua plataforma de deploy (Railway, Render, Google Cloud Run, etc) usando a imagem ${{ secrets.DOCKERHUB_USERNAME }}/smartcollect:${{ github.sha }}"
